### ISSUE TITLE
levelUP / levelDOWN runtime error with `npm run start:dev`

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#28]
`npm install` concludes with a full successful rebuild to target Electron (1.7.9/1.7.10), but the app starts with an error (see console message below). Any idea? Are you experiencing the same at your end?

```
[1] App threw an error during load
[1] AssertionError: .status required, old abstract-leveldown
[1]     at new LevelUP (/Users/danielweck/Code/readium-desktop/dist/main.js:69273:10)
[1]     at LevelUP (/Users/danielweck/Code/readium-desktop/dist/main.js:69250:12)
[1]     at PouchDB$2.LevelPouch (/Users/danielweck/Code/readium-desktop/dist/main.js:67882:144)
[1]     at PouchDB$2.JsonDownPouch (/Users/danielweck/Code/readium-desktop/dist/main.js:67611:83)
[1]     at new PouchDB$2 (/Users/danielweck/Code/readium-desktop/dist/main.js:17751:36)
[1]     at Object.<anonymous> (/Users/danielweck/Code/readium-desktop/dist/main.js:5592:23)
[1]     at __webpack_require__ (/Users/danielweck/Code/readium-desktop/dist/main.js:21:30)
[1]     at Object.<anonymous> (/Users/danielweck/Code/readium-desktop/dist/main.js:47451:14)
[1]     at __webpack_require__ (/Users/danielweck/Code/readium-desktop/dist/main.js:21:30)
[1]     at /Users/danielweck/Code/readium-desktop/dist/main.js:64:18
```

**Comment by danielweck** [comment]
Oh, works fine with `npm run start` (instead of `npm run start:dev`). I think that's normal, right?

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/readium-desktop/commit/faf8a1dbe2f30a0f6d6373b38f10e69ff93bd9c8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
(also see original cherry-pick: https://github.com/edrlab/readium-desktop/commit/409c210c2d6cc9a82b5cedceb0923c0db8433b27 )
