### ISSUE TITLE
when import EPUB (into library) with multilingual title: React crash (requires deleting database)

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#34]
The Readium2 webpub manifest can contain metadata title with map object instead of single string value, for example:

```json
{ "en": "Mahabharata" }
```

=> this kills the library view, and happens again after closing+reopening the application.

The Redux Store state that causes problems is `store.catalog.publications[i].title` (object type instead of string)

**Comment by danielweck** [comment]
```
Warning: Failed prop type: Invalid prop `title` supplied to `CardTitle`, expected a ReactNode.
    in CardTitle (created by PublicationListElement)
    in PublicationListElement (created by Library)
    in div (created by Library)
    in div (created by Library)
    in Library (created by App)
    in div (created by Dropzone)
    in Dropzone (created by App)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App
```

**Comment by danielweck** [comment]
```
Uncaught Error: Objects are not valid as a React child (found: object with keys {en}). If you meant to render a collection of children, use an array instead.
    in span (created by CardTitle)
    in div (created by CardTitle)
    in CardTitle (created by PublicationListElement)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by PublicationListElement)
    in div (created by PublicationListElement)
    in PublicationListElement (created by Library)
    in div (created by Library)
    in div (created by Library)
    in Library (created by App)
    in div (created by Dropzone)
    in Dropzone (created by App)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App
    at invariant (invariant.js:42)
    at throwOnInvalidObjectType (react-dom.development.js:6748)
    at reconcileChildFibers (react-dom.development.js:7659)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:7756)
    at reconcileChildren (react-dom.development.js:7747)
    at updateHostComponent (react-dom.development.js:7998)
    at beginWork (react-dom.development.js:8229)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
```

**Comment by danielweck** [comment]
```
The above error occurred in the <span> component:
    in span (created by CardTitle)
    in div (created by CardTitle)
    in CardTitle (created by PublicationListElement)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by PublicationListElement)
    in div (created by PublicationListElement)
    in PublicationListElement (created by Library)
    in div (created by Library)
    in div (created by Library)
    in Library (created by App)
    in div (created by Dropzone)
    in Dropzone (created by App)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App

```

**Comment by danielweck** [comment]
```
uncaught at rootSaga Error: Objects are not valid as a React child (found: object with keys {en}). If you meant to render a collection of children, use an array instead.
    in span (created by CardTitle)
    in div (created by CardTitle)
    in CardTitle (created by PublicationListElement)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by PublicationListElement)
    in div (created by PublicationListElement)
    in PublicationListElement (created by Library)
    in div (created by Library)
    in div (created by Library)
    in Library (created by App)
    in div (created by Dropzone)
    in Dropzone (created by App)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App
Invariant Violation: Objects are not valid as a React child (found: object with keys {en}). If you meant to render a collection of children, use an array instead.
    in span (created by CardTitle)
    in div (created by CardTitle)
    in CardTitle (created by PublicationListElement)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by PublicationListElement)
    in div (created by PublicationListElement)
    in PublicationListElement (created by Library)
    in div (created by Library)
    in div (created by Library)
    in Library (created by App)
    in div (created by Dropzone)
    in Dropzone (created by App)
    in div (created by App)
    in MuiThemeProvider (created by App)
    in App
    at invariant (http://localhost:8080/index_app.js:10962:15)
    at throwOnInvalidObjectType (http://localhost:8080/index_app.js:49390:5)
    at reconcileChildFibers (http://localhost:8080/index_app.js:50301:7)
    at reconcileChildrenAtExpirationTime (http://localhost:8080/index_app.js:50398:30)
    at reconcileChildren (http://localhost:8080/index_app.js:50389:5)
    at updateHostComponent (http://localhost:8080/index_app.js:50640:5)
    at beginWork (http://localhost:8080/index_app.js:50871:16)
    at performUnitOfWork (http://localhost:8080/index_app.js:52866:16)
    at workLoop (http://localhost:8080/index_app.js:52930:26)
    at HTMLUnknownElement.callCallback (http://localhost:8080/index_app.js:43184:14)
```

**Comment by danielweck** [comment]
@clebeaupin this bug is addressed in the `feature/r2-navigator-refactor` branch (so the app does not crash on startup). I implemented a temporary / incomplete fix though: I left the Publication database model untouched (i.e. `title` field is declared as string, but can in fact be an object / string key/value map for multilingual publications), and the `Publication.title` property is converted to a single string based on a given language. This language is currently hard-coded to "en" (with a fallback to the first available language from the object). I added TODO comments to correct this at a later stage, for example: pick-up the user preference from the shared application state (user language).

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/readium-desktop/commit/e7c18cb1dcfdb513ed5aad854b1daa457af0d83a

**Comment by danielweck** [comment]
For your information, here is a recent message from Hadrien about multilingual string values in Readium webpub manifest:
https://github.com/w3c/wpub/issues/124#issue-291244334

**Comment by danielweck** [comment]
The aforementioned WPUB discussion references a very interesting document:
https://w3c.github.io/string-meta/#bestPractices
We *may* (maybe) have to update the multi-lang model of `Publication.Title` (and all other properties of a similar string type) in order to include `dir` in addition to `lang`.
This means that the `getTitleString()` function might need to be updated.

**Comment by danielweck** [comment]
@clebeaupin this bug also applies to `author` / `contributor` (not just `title`). The app does not instantly crash in this case, but there is a bogus object displayed in the user interface instead of a string of characters, below EPUB cover image, etc.
Easily reproducible with "Regime Anti-Cancer Arabic" 
https://idpf.github.io/epub3-samples/30/samples.html#regime-anticancer-arabic
...and "Mahabharata" for the full crash:
https://idpf.github.io/epub3-samples/30/samples.html#mahabharata

Good news: this is all fixed in `feature/next-latest-r2`, so feel free to merge the branch into `feature/next`, but please leave the Pull Request open:
https://github.com/edrlab/readium-desktop/pull/40
(as this one tracks ongoing developments)

**Comment by danielweck** [comment]
Both `title` and `author` fixed here: https://github.com/edrlab/readium-desktop/commit/5c130212d4ad56f8c9b7fa2896bc341405e33c93
