### ISSUE TITLE
RangeError: Invalid time value for some EPUBs (date/time metadata)

### ISSUE THREAD

**Issue by danielweck** [edrlab/readium-desktop#54]
`RangeError: Invalid time value`

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: --T00:00:00Z, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (r2-testapp-js/node_modules/moment/moment.js:324:94)
    at configFromString (r2-testapp-js/node_modules/moment/moment.js:2366:11)
    at configFromInput (r2-testapp-js/node_modules/moment/moment.js:2592:9)
    at prepareConfig (r2-testapp-js/node_modules/moment/moment.js:2575:9)
    at createFromConfig (r2-testapp-js/node_modules/moment/moment.js:2542:40)
    at createLocalOrUTC (r2-testapp-js/node_modules/moment/moment.js:2629:12)
    at createLocal (r2-testapp-js/node_modules/moment/moment.js:2633:12)
    at hooks (r2-testapp-js/node_modules/moment/moment.js:16:25)
    at fillPublicationDate (r2-testapp-js/node_modules/r2-shared-js/dist/es8-es2017/src/parser/epub.js:624:52)
    at Object.EpubParsePromise (r2-testapp-js/node_modules/r2-shared-js/dist/es8-es2017/src/parser/epub.js:332:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by danielweck** [comment]
TODO: daniel to check parsing code in r2-xxx-js, find workaround for invalid metadata format

**Comment by danielweck** [comment]
Yep, `<dc:date>--T00:00:00Z</dc:date>`

**Comment by danielweck** [comment]
We need a sanity check in the parser code, and ignore broken values. I wonder if EPUB-Check captures these types of errors?

**Comment by danielweck** [comment]
EPUB-Check emits a warning, not an error:
WARNING(OPF-053): xxx.epub/OEBPS/content.opf(12,34): Date value '--T00:00:00Z' does not follow recommended syntax as per http://www.w3.org/TR/NOTE-datetime:[For input string: "-"] is not an integer.

**Comment by danielweck** [comment]
Should be fixed in: https://github.com/edrlab/r2-shared-js/commit/947ddd80462d61d692722df9a545a8281b300b58
(testing with both `readium-desktop` and `r2-testapp-js`.

**Comment by danielweck** [comment]
Ah, `moment().isValid()` does the job (otherwise "empty" invalid object placeholders are created!
https://github.com/edrlab/r2-shared-js/commit/130f9a6d6f5ce464650511448436ff6c3818742d
